GPU: '0'
b1: 0.5
b2: 0.999
batch_size: 1
blindspot: true
datasets_folder: '20221119'
datasets_path: datasets
f_num: 8
img_h: 144
img_s: 32
img_w: 144
in_c: 15
in_c_s: 15
in_c_t: 8
lr: 0.0001
n_epochs: 100
net_type: T3XY3
norm_factor: 1
out_c: 1
output_dir: ./results
output_path: ./results/DeepSeMi_T3XY3_20221119_202306150740
pretrain_index: ''
pretrain_model: datasets
pretrain_path: ''
pth_path: pth
pth_save_path: pth//DeepSeMi_T3XY3_20221119_202306150740
select_img_num: 5000
train_datasets_size: 1000
use_pretrain: 0
