GPU: 0,1,4
b1: 0.5
b2: 0.999
batch_size: 3
blindspot: true
datasets_folder: pretrain_datasets
datasets_path: ..//datasets
f_num: 32
img_h: 192
img_s: 32
img_w: 192
in_c: 31
in_c_s: 31
in_c_t: 16
lr: 0.0001
n_epochs: 20
net_type: T3XY3
norm_factor: 1
out_c: 1
output_dir: ./results
output_path: ./results/DeepSeMi_T3XY3_pretrain_d_202306031141
pretrain_index: deepsemi_49.pth
pretrain_model: DeepSeMi_T1XY1_pretrain_d_f32
pretrain_path: pth_XYS
pth_path: pth_XYS
pth_save_path: pth_XYS//DeepSeMi_T3XY3_pretrain_d_202306031141
select_img_num: 5000
train_datasets_size: 1000
use_pretrain: 1
